# Generated by Django 6.0.5 on 2026-06-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccount',
            name='enable_any_employee_option',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='show_staff_names_publicly',
            field=models.BooleanField(default=True),
        ),
    ]
