# Generated by Django 6.0.5 on 2026-06-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_accounts', '0002_add_settings_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccount',
            name='booking_confirmation_mode',
            field=models.CharField(choices=[('automatic', 'Automatic confirmation'), ('manual', 'Manual confirmation')], default='automatic', max_length=20),
        ),
    ]
