# Generated by Django 6.0.5 on 2026-06-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_accounts', '0003_booking_confirmation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccount',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='plz',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='street',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='website',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
