# Generated by Django 6.0.5 on 2026-06-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_accounts', '0004_add_address_and_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccount',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('fr', 'Français'), ('it', 'Italiano'), ('en', 'English')], default='de', help_text='Language used for your dashboard, public booking page, and notification emails.', max_length=2, verbose_name='Interface language'),
        ),
    ]
