# Generated by Django 6.0.5 on 2026-06-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_accounts', '0005_companyaccount_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccount',
            name='tos_accepted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='tos_version',
            field=models.CharField(default='', max_length=20),
        ),
    ]
