# Generated by Django 6.0.5 on 2026-06-17 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_accounts', '0006_add_tos_accepted_at_and_tos_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_email_hash', models.CharField(db_index=True, max_length=64)),
                ('business_name', models.CharField(max_length=255)),
                ('deletion_token', models.CharField(max_length=64)),
                ('requested_at', models.DateTimeField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
