# Generated by Django 6.0.5 on 2026-06-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_accounts', '0007_add_deletion_request_and_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccount',
            name='slot_interval_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
