# Generated by Django 6.0.5 on 2026-06-04 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff_members', '0002_rename_staff_membe_company_idx_staff_membe_company_29080c_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offerings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_service_offerings', to='services.serviceoffering')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_service_offerings', to='staff_members.staffmember')),
            ],
        ),
        migrations.AddIndex(
            model_name='serviceoffering',
            index=models.Index(fields=['company'], name='services_se_company_5c4c35_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceoffering',
            index=models.Index(fields=['is_active'], name='services_se_is_acti_375532_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceoffering',
            index=models.Index(fields=['duration_minutes'], name='services_se_duratio_ff50e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffserviceoffering',
            constraint=models.UniqueConstraint(fields=('staff_member', 'service_offering'), name='unique_staff_service_offering'),
        ),
    ]
