# Generated by Django 6.0.5 on 2026-06-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_members', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffmember',
            new_name='staff_membe_company_29080c_idx',
            old_name='staff_membe_company_idx',
        ),
    ]
