# Generated by Django 6.0.5 on 2026-06-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_appointmentslot_staff_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentslot',
            options={'ordering': ['start_at'], 'verbose_name': 'Open Hours', 'verbose_name_plural': 'Open Hours'},
        ),
        migrations.RenameIndex(
            model_name='appointmentslot',
            new_name='availabilit_staff_m_2ffdb3_idx',
            old_name='availabilit_staff_m_idx',
        ),
    ]
