# Generated by Django 6.0.5 on 2026-06-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_alter_appointmentslot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked'), ('pending_confirmation', 'Pending Confirmation')], default='available', max_length=20),
        ),
    ]
