# Generated by Django 6.0.5 on 2026-06-04 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('availability', '0003_alter_appointmentslot_options_and_more'),
        ('services', '0001_initial'),
        ('staff_members', '0002_rename_staff_membe_company_idx_staff_membe_company_29080c_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('customer_message', models.TextField(blank=True, default='')),
                ('privacy_accepted_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('public_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='availability.appointmentslot')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('service_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.serviceoffering')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='staff_members.staffmember')),
            ],
            options={
                'indexes': [models.Index(fields=['company'], name='bookings_bo_company_015739_idx'), models.Index(fields=['staff_member'], name='bookings_bo_staff_m_5dca30_idx'), models.Index(fields=['service_offering'], name='bookings_bo_service_419313_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'), models.Index(fields=['start_at'], name='bookings_bo_start_a_042c97_idx'), models.Index(fields=['created_at'], name='bookings_bo_created_1720a2_idx'), models.Index(fields=['public_token'], name='bookings_bo_public__a1a275_idx')],
            },
        ),
    ]
