# Generated by Django 6.0.5 on 2026-06-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_pending_declined_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='privacy_policy_version',
            field=models.CharField(default='', max_length=20),
        ),
    ]
